# Generated by Django 4.2.6 on 2024-01-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='family',
            new_name='Family',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='family',
            new_name='Family',
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
