# Generated by Django 4.2.6 on 2024-01-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPApp', '0003_alter_user_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
        migrations.AddField(
            model_name='user',
            name='imageUrl',
            field=models.CharField(default='https://raspi/martin.amor/pp-backend/raw/master/PPAPI/PPApp/los_pinguinos.jpg', max_length=500),
        ),
    ]
