# Generated by Django 4.2.6 on 2024-02-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPApp', '0002_alter_products_price'),
        ('PPApp', '0004_remove_user_image_url_user_imageurl'),
    ]

    operations = [
    ]
