# Generated by Django 4.2.6 on 2024-02-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPApp', '0006_alter_user_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Family',
            new_name='family',
        ),
    ]
