# Generated by Django 4.2.6 on 2024-02-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPApp', '0007_rename_family_user_family'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='Family',
            new_name='family',
        ),
    ]
